name: ci-pr
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build .
